
name: Deploy to Firebase Functions on merge
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - functions/**
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
        working-directory: functions

      - name: Set FIREBASE_PROJECT_ID
        run: |
          echo "export const projectId = '${{ secrets.FIREBASE_PROJECT_ID }}'" >> src/environment.ts

      - uses: aronep6/action-functions-deploy@v1.0.0
        with:
          serviceAccountKey: ${{ secrets.FIREBASE_DEPLOY_SERVICE_ACCOUNT_KEY }}
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
