
name: Deploy to Firebase Hosting on merge
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci

      - run: |
          echo "export const environment = {
            firebaseConfig: {
              apiKey: '${{ secrets.FIREBASE_API_KEY }}',
              authDomain: '${{ secrets.FIREBASE_PROJECT_ID }}.firebaseapp.com',
              projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
              storageBucket: '${{ secrets.FIREBASE_PROJECT_ID }}.firebasestorage.app',
              messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
              appId: '${{ secrets.FIREBASE_APP_ID }}'
            },
            appCheckSiteKey: '${{ secrets.APP_CHECK_SITE_KEY }}'
          };" > src/environments/environment.ts
        shell: bash

      - name: Replace PROJECT_ID in .firebaserc
        run: |
          sed -i 's/{{PROJECT_ID}}/${{ secrets.FIREBASE_PROJECT_ID }}/g' .firebaserc
        shell: bash

      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_DEPLOY_SERVICE_ACCOUNT_KEY }}
          channelId: live
          projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
